fix(bin): update smartypants bin script to use smartypants package names

diff --git a/packages/smartypants/bin/smartypants b/packages/smartypants/bin/smartypants
--- a/packages/smartypants/bin/smartypants
+++ b/packages/smartypants/bin/smartypants
@@ -32,9 +32,9 @@ else
         *) arch="$(uname -m)" ;;
     esac
     
-    name="opencode-${platform}-${arch}"
-    binary="opencode"
-    [ "$platform" = "win32" ] && binary="opencode.exe"
+    name="smartypants-${platform}-${arch}"
+    binary="smartypants"
+    [ "$platform" = "win32" ] && binary="smartypants.exe"
     
     # Search for the binary starting from real script location
     resolved=""
@@ -49,7 +49,7 @@ else
     done
     
     if [ -z "$resolved" ]; then
-        printf "It seems that your package manager failed to install the right version of the opencode CLI for your platform. You can try manually installing the \"%s\" package\n" "$name" >&2
+        printf "It seems that your package manager failed to install the right version of the smartypants CLI for your platform. You can try manually installing the \"%s\" package\n" "$name" >&2
         exit 1
     fi
 fi
